//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGP.Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NGP.Foundation.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成文件失败 的本地化字符串。
        /// </summary>
        public static string CreateFileError {
            get {
                return ResourceManager.GetString("CreateFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string DropDownDefaultName {
            get {
                return ResourceManager.GetString("DropDownDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string DropDownSelectName {
            get {
                return ResourceManager.GetString("DropDownSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有对该数据的授权，不能操作！ 的本地化字符串。
        /// </summary>
        public static string DynamicResourceAuthError {
            get {
                return ResourceManager.GetString("DynamicResourceAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已经存在！ 的本地化字符串。
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}格式错误，正确的格式是 {1}！ 的本地化字符串。
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已经被删除，请刷新后重试！ 的本地化字符串。
        /// </summary>
        public static string HasBeenDeleted {
            get {
                return ResourceManager.GetString("HasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能超过{1}长度！ 的本地化字符串。
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须小于{1} 的本地化字符串。
        /// </summary>
        public static string MustLessThan {
            get {
                return ResourceManager.GetString("MustLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的批号{0}不需要续传 的本地化字符串。
        /// </summary>
        public static string NoBatchDetail {
            get {
                return ResourceManager.GetString("NoBatchDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单未设定批号 的本地化字符串。
        /// </summary>
        public static string NoBatchKey {
            get {
                return ResourceManager.GetString("NoBatchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无冗余关系！ 的本地化字符串。
        /// </summary>
        public static string NoRelationError {
            get {
                return ResourceManager.GetString("NoRelationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许上传空白附件! 的本地化字符串。
        /// </summary>
        public static string NotAllowBlank {
            get {
                return ResourceManager.GetString("NotAllowBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空！ 的本地化字符串。
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}和{1}不符合记录 的本地化字符串。
        /// </summary>
        public static string NotMeetTheRecord {
            get {
                return ResourceManager.GetString("NotMeetTheRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计总个数小于错误个数{0},{1} 的本地化字符串。
        /// </summary>
        public static string NoTotalError {
            get {
                return ResourceManager.GetString("NoTotalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        public static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string RownumberName {
            get {
                return ResourceManager.GetString("RownumberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已经被使用，不能操作！ 的本地化字符串。
        /// </summary>
        public static string SaveValidationError {
            get {
                return ResourceManager.GetString("SaveValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
